### ISSUE TITLE
jquery 2.x suggestion

### ISSUE THREAD

**Issue by Lechus** [buildingblocks/bb-prototype-website#11]
In place of:
However, do not update jQuery to 2.x unless you are dropping support for Internet Explorer 6, 7, and 8.

You can add to template something like that:
```
@*jQuery v1/v2 conditional loading & html5siv*@
        <!--[if lt IE 9]>
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-1.10.2.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.min.js"></script>
            <script>
            window.jQuery || document.write('<script src="/scripts/jquery-1.10.2.min.js"><\/script>')
	        </script>
        <![endif]-->
        <!--[if gte IE 9]><!-->
            <script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
            <script>
                window.jQuery || document.write('<script src="/scripts/jquery-2.0.3.min.js"><\/script>')                
            </script>
        <!--<![endif]-->
```

**Comment by Lechus** [comment]
fix embedding code

**Comment by furzeface** [comment]
I'm afraid this wouldn't work for our scenario, we choose to upgrade to jQuery on a case-by-case basis. 
I don't think that this would work in the case that backward incompatible jQuery based code is written - if something that works in 2.x + and not when using the earlier versions that code wouldn't run in LTIE9 if the jQuery method didn't exist. 

Plus our [Yeoman generator](https://github.com/frontendfriends/generator-bb-project) when finished will allow you to choose! :smile: 

Thank you for your input though.

Regards,
Dan.
