### ISSUE TITLE
add npm shrinkwrap

### ISSUE THREAD

**Issue by PJL101** [buildingblocks/bb-prototype-website#15]
* Based on: https://github.com/Akuda/fedkit-assemble/issues/31
* Docs: https://docs.npmjs.com/cli/shrinkwrap

There is a chance that node modules could be different even when using the same package.json.

Real world example: grunt-sass uses the latest version of node-sass which uses the latest version of libsass. This means that team members can use different versions of libsass on the same project.

**Comment by furzeface** [comment]
:+1:

**Comment by furzeface** [comment]
Go through this on FedKit with me some time @PJL101?

**Comment by PJL101** [comment]
Can do. Iampjl.co.uk has a working example in the meantime.
